### ISSUE TITLE
Support for UTF8

### ISSUE THREAD

**Issue by yanoksy** [jorgebastida/django-dajax#11] opened 2010-05-26 04:05 UTC
Could not be used with Spanish or other language with accents.

**Comment by jorgebastida** [comment] 2010-05-26 07:09
Can you share some code to reproduce the error. (Traceback, example... something)
Thanks!

**Comment by bernie2004** [comment] 2010-06-10 18:12
replace escape into encodeURIComponent in dajaxice  / templates  / dajaxice  / dajaxice.core.js line 10:
send_data.push('argv='+encodeURIComponent(JSON.stringify(argv)));

at least that's what works for me

**Comment by jnohlgard** [comment] 2010-06-29 14:25
Works like a charm!
See also: http://xkr.us/articles/javascript/encode-compare/
escape() encodes everything to its iso8859-1 representation, which is a bad choice since Django uses unicode internally.

**Comment by jorgebastida** [comment] 2010-07-06 19:06
Fixing this bug in dajaxice. Will be released in django-dajaxice-0.1.5

**Closed as completed** 2010-07-07 04:11 UTC
Labels: acepted

**Comment by jorgebastida** [comment] 2010-08-12 11:31
Doesn't fixed in 0.1.5 , i will reopen the ticket and fix it.
